RNPM.Web/Controllers/HomeController.cs
using System.Diagnostics;
using System.IdentityModel.Tokens.Jwt;
using System.Net;
using System.Security.Claims;
using AspNetCoreHero.ToastNotification.Abstractions;
using Dohwe.Web.Extensions;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using RNPM.API.ViewModels;
using RNPM.Common.Constants;
using RNPM.Common.ViewModels;
using RNPM.Common.ViewModels.Core;
using RNPM.Common.ViewModels.UserManagement;
using RNPM.Web.Models;
using LoginViewModel = RNPM.Common.ViewModels.LoginViewModel;

namespace RNPM.Web.Controllers;
[Authorize]
public class HomeController : BaseController<HomeController>
{
    private readonly ILogger<HomeController> _logger;
    private readonly INotyfService _notyfService;
    public HomeController(ILogger<HomeController> logger, INotyfService notifyService)
    {
        _logger = logger;
        _notyfService = notifyService;
    }
    
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        await SetData();

        return View();
    }
    
        private async Task SetData()
        {
           var applications = await Get<List<ApplicationViewModel>>(await GetHttpClient(), "api/applications/getuserapplications",
                    GetUserId());
                ViewBag.Applications = applications;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> CreateApplication([Bind($"Name")] string name)
        {
            var userId = GetUserId();
            if (userId == null)
            {
                _notyfService.Error("An error occured");
                return RedirectToAction("Index");
            }
            var model = new CreateApplicationViewModel()
            {
                Name = name,
                UserId = GetUserId()
            };
            if (model.Name != "" || model.UserId != "")
            {
                var applicationCreation = await Add<ApplicationViewModel, CreateApplicationViewModel>(await GetHttpClient(), "api/applications/createapplication", model);
                if ( applicationCreation.Status != (int)HttpStatusCode.OK)
                {
                    ModelState.AddModelError("", applicationCreation.Title);
                    _notyfService.Error(applicationCreation.Title);

                    return RedirectToAction("Index");
                }
                var application = applicationCreation.Result;
                _notyfService.Success(applicationCreation.Title);
                await SetData();
                return RedirectToAction("Index");
            }

            await SetData();
            ViewBag.Message = "applicationCreation.Title";

            return RedirectToAction("Index");
        }
        public async Task<ActionResult> DeleteApplication(string id)
        {
            var applicationToDelete = await Get<ApplicationViewModel>(await GetHttpClient(),
                "api/applications/getApplication", id);
            
            var component = await Remove<ApplicationViewModel>(await GetHttpClient(), "api/applications/deleteApplicationById", id);
            if (component.Status == (int)HttpStatusCode.OK)
            {
                _notyfService.Error("Failed to delete! Contact system administrator");
            }
            else
            {
                _notyfService.Success(component.Title);
            }
            return RedirectToAction("Index");
        }
        public async Task<ActionResult> Dashboard(string id)
        {
            var application = await Get<ApplicationViewModel>(await GetHttpClient(), "api/applications/GetApplication", id);
            var applicationId = application.Id;
            await SetData();
            ViewData["Application"] = application;
            ViewBag.Application = application;
            var components = await Get<List<ScreenComponentViewModel>>(await GetHttpClient(),
                "api/screenComponents/getComponents", applicationId);
            var navigations = await Get<List<NavigationViewModel>>(await GetHttpClient(),
                "api/navigations/getNavigations", applicationId);
            var networkRequests = await Get<List<NetworkRequestViewModel>>(await GetHttpClient(),
                "api/networkRequests/getNetworkRequests", applicationId);
            ViewBag.ScreenComponents = components;
            ViewBag.Navigations = navigations;
            ViewBag.NetworkRequests = networkRequests;
            return View(application);
        }
        

        
}

RNPM.Web/Controllers/NavigationsController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RNPM.Common.ViewModels.Core;

namespace RNPM.Web.Controllers;
[Authorize]
public class NavigationsController : BaseController<NavigationsController>
{
    private readonly ILogger<NavigationsController> _logger;
    private readonly INotyfService _notyfService;

    public NavigationsController(ILogger<NavigationsController> logger, INotyfService notifyService)
    {
        _logger = logger;
        _notyfService = notifyService;
    }
    
    [HttpGet]
    public async Task<IActionResult> Index(string id)
    {
        if (id != null)
        {
            await SetData(id);
            return View();
        }
        else
        {
            return RedirectToAction("Index", "Home");
        }
    }
    
    private async Task SetData(string navigationId)
    {
        var applications = await Get<List<ApplicationViewModel>>(await GetHttpClient(), "api/applications/getuserapplications",
            GetUserId());
        var navigation = await Get<NavigationViewModel>(await GetHttpClient(), "api/Navigations/getNavigation", navigationId);
        var navigationAverages = await Get<List<DailyAverageViewModel>>(await GetHttpClient(), "api/Navigations/getNavigationAverages", navigationId);
        ViewBag.Applications = applications;
        ViewBag.NavigationAverages = navigationAverages;
        ViewBag.Navigation = navigation;
        
    }
        
    public async Task<ActionResult> DeleteNavigation(string id)
    {
        var navigationToDelete = await Get<NavigationViewModel>(await GetHttpClient(),
            "api/navigations/getNavigation", id);
            
        var component = await Remove<NavigationViewModel>(await GetHttpClient(), "api/navigations/deleteNavigationById", id);
            
        //return Json(value);
        return RedirectToAction("Dashboard","Home", new {id = navigationToDelete.ApplicationId});
    }
        
}

RNPM.Web/Controllers/RendersController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RNPM.Common.ViewModels.Core;

namespace RNPM.Web.Controllers;
[Authorize]
public class RendersController : BaseController<RendersController>
{
    private readonly ILogger<RendersController> _logger;
    private readonly INotyfService _notyfService;

    public RendersController(ILogger<RendersController> logger, INotyfService notifyService)
    {
        _logger = logger;
        _notyfService = notifyService;
    }
    
    [HttpGet]
    public async Task<IActionResult> Details(string id)
    {
        if (id != null)
        {
            await SetData(id);
            return View();
        }
        else
        {
           return RedirectToAction("Index", "Home");
        }
    }
    
        private async Task SetData(string componentId)
        {
           var applications = await Get<List<ApplicationViewModel>>(await GetHttpClient(), "api/applications/getuserapplications",
                    GetUserId());
           var component = await Get<ComponentViewModel>(await GetHttpClient(), "api/screenComponents/getComponent", componentId);
           var renderAverages = await Get<List<DailyAverageViewModel>>(await GetHttpClient(), "api/screenComponents/getRenderTimeAverages", componentId);
            ViewBag.Applications = applications;
            ViewBag.ScreenComponent = component;
            ViewBag.RenderAverages = renderAverages;
        }
        
        public async Task<ActionResult> DeleteComponent(string id)
        {
            var componentToDelete = await Get<ScreenComponentViewModel>(await GetHttpClient(),
                "api/screenComponents/getComponent", id);
            
            var component = await Remove<ScreenComponentViewModel>(await GetHttpClient(), "api/screenComponents/deleteComponentById", id);
            
            //return Json(value);
            return RedirectToAction("Dashboard","Home", new {id = componentToDelete.ApplicationId});
        }
        
}

RNPM.Web/Controllers/RequestsController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RNPM.Common.ViewModels.Core;

namespace RNPM.Web.Controllers;
[Authorize]
public class RequestsController : BaseController<RequestsController>
{
    private readonly ILogger<RequestsController> _logger;
    private readonly INotyfService _notyfService;

    public RequestsController(ILogger<RequestsController> logger, INotyfService notifyService)
    {
        _logger = logger;
        _notyfService = notifyService;
    }
    
    [HttpGet]
    public async Task<IActionResult> Index(string id)
    {
        if (id != null)
        {
            await SetData(id);
            return View();
        }
        else
        {
            return RedirectToAction("Index", "Home");
        }
    }
    
    private async Task SetData(string requestId)
    {
        var applications = await Get<List<ApplicationViewModel>>(await GetHttpClient(), "api/applications/getuserapplications",
            GetUserId());
        var request = await Get<NetworkRequestViewModel>(await GetHttpClient(), "api/NetworkRequests/getNetworkRequest", requestId);
        var requestAverages = await Get<List<DailyAverageViewModel>>(await GetHttpClient(), "api/NetworkRequests/getNetworkRequestAverages", requestId);
        ViewBag.Applications = applications;
        ViewBag.Request = request;
        ViewBag.RequestAverages = requestAverages;
    }
        
    public async Task<ActionResult> DeleteRequest(string id)
    {
        var requestToDelete = await Get<NetworkRequestViewModel>(await GetHttpClient(),
            "api/navigations/getNavigation", id);
            
        var request = await Remove<NetworkRequestViewModel>(await GetHttpClient(), "api/networkRequests/deleteNetworkRequestById", id);
            
        //return Json(value);
        return RedirectToAction("Dashboard","Home", new {id = requestToDelete.ApplicationId});
    }
        
}

RNPM.Web/Views/Home/Dashboard.cshtml
@using RNPM.Common.ViewModels.Core
@{
    ViewData["Title"] = "Dashboard";
}
@{
    var application = (ApplicationViewModel)ViewBag.Application;
    var components = (IEnumerable<ScreenComponentViewModel>)ViewBag.ScreenComponents;
    var navigations = (IEnumerable<NavigationViewModel>)ViewBag.Navigations;
    var networkRequests = (IEnumerable<NetworkRequestViewModel>)ViewBag.NetworkRequests;
}

<div id="content" class="app-content">

    <ol class="breadcrumb float-xl-end">
    </ol>

    <h1 class="page-header">@application.Name <small>Unique Access Code --- @application.UniqueAccessCode</small></h1>

    <div class="row">

        <div class="col-xl-4 col-md-6">
            <div class="widget widget-stats bg-blue">
                <div class="stats-icon"><i class="fa fa-mobile"></i></div>
                <div class="stats-info">
                    <h4>Managed Components</h4>
                    <p>@components.Count()</p>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-md-6">
            <div class="widget widget-stats bg-info">
                <div class="stats-icon"><i class="fa fa-code-compare"></i></div>
                <div class="stats-info">
                    <h4>Managed Navigations</h4>
                    <p>@navigations.Count()</p>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-md-6">
            <div class="widget widget-stats bg-orange">
                <div class="stats-icon"><i class="fa fa-link"></i></div>
                <div class="stats-info">
                    <h4>Managed Requests</h4>
                    <p>@networkRequests.Count()</p>
                </div>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-12 flex-1">
            <ul class="nav nav-tabs nav-tabs-inverse nav-justified" data-sortable-id="index-2">
                <li class="nav-item">
                    <a href="#component-renders" data-bs-toggle="tab" class="nav-link active"><i class="fa fa-mobile fa-lg me-5px"></i><span class="d-none d-md-inline">Managed Component Renders</span></a>
                </li>
                <li class="nav-item"><a href="#navigations" data-bs-toggle="tab" class="nav-link"><i class="fa fa-code-compare fa-lg me-5px"></i> <span class="d-none d-md-inline">Managed Navigations</span></a></li>
                <li class="nav-item"><a href="#requests" data-bs-toggle="tab" class="nav-link"><i class="fa fa-link fa-lg me-5px"></i> <span class="d-none d-md-inline">Managed Network Requests</span></a></li>
            </ul>
            <div class="tab-content panel rounded-0 rounded-bottom mb-20px " data-sortable-id="index-3">
                <div class="tab-pane fade active show" id="component-renders">
                    <div class=" h-500px widget-list " data-scrollbar="true" data-id="widget">
                        @if (components?.Count() > 0)
                        {
                            @foreach (var item in components)
                            {
                                <div class="widget-list-item border-bottom row">
                                    <div class="widget-list-content col-xl-10 col-lg-8">
                                        <a href="@Url.Action("Details", "Renders", new { id = item.Id })">
                                            <h4 class="widget-list-title">@item.Name</h4>
                                        </a>
                                    </div>
                                    <div class="widget-list-action text-end col-xl-2 col-lg-4">
                                        <a href="@Url.Action("DeleteComponent", "Renders", new { id = item.Id })">
                                            <i class="fa fa-trash fa-lg text-red text-body text-opacity-30"></i>
                                        </a>
                                    </div>
                                </div>
                            }
                        }
                        else
                        {
                            <p>No managed components</p>
                        }

                    </div>
                </div>
                <div class="tab-pane fade" id="navigations">
                    <div class=" h-500px widget-list " data-scrollbar="true" data-id="widget">
                        @if (navigations?.Count() > 0)
                        {
                            foreach (var item in navigations)
                            {
                                <div class="widget-list-item border-bottom row">
                                    <div class="widget-list-content col-xl-10 col-lg-8">
                                        <a href="@Url.Action("Index", "Navigations", new { id = item.Id })">
                                            <h4 class="widget-list-title">@item.FromScreen ----> @item.ToScreen</h4>
                                        </a>
                                    </div>
                                    <div class="widget-list-action text-end col-xl-2 col-lg-4">
                                        <a href="@Url.Action("DeleteNavigation", "Navigations", new { id = item.Id })">
                                            <i class="fa fa-trash fa-lg text-red text-body text-opacity-30"></i>
                                        </a>
                                    </div>
                                </div>
                            }
                        }
                        else
                        {
                            <p>No managed Navigations</p>
                        }
                    </div>
                </div>
                <div class="tab-pane fade" id="requests">
                    <div class=" h-500px widget-list " data-scrollbar="true" data-id="widget">
                        @if (navigations?.Count() > 0){
                        foreach (var item in networkRequests)
                        {
                            <div class="widget-list-item border-bottom row">
                                <div class="widget-list-content col-xl-10 col-lg-8">
                                    <a href="@Url.Action("Index", "Requests", new { id = item.Id })">
                                        <h4 class="widget-list-title">@item.Name</h4>
                                    </a>
                                </div>
                                <div class="widget-list-action text-end col-xl-2 col-lg-4">
                                    <a href="@Url.Action("DeleteRequest", "Requests", new { id = item.Id })">
                                        <i class="fa fa-trash fa-lg text-red text-body text-opacity-30"></i>
                                    </a>
                                </div>
                            </div>
                        }
                        }
                        else
                        {
                            <p>No managed Network Requests</p>
                        }
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

RNPM.Web/Views/Home/Index.cshtml
@using RNPM.Common.ViewModels.Core
@model RNPM.Common.ViewModels.Core.CreateApplicationViewModel
@{
    ViewData["Title"] = "Home";
    Layout = "_ApplicationsLayout";
}
@{
    var applications = (IEnumerable<ApplicationViewModel>)ViewBag.Applications;
}

<div id="content" class="app-content align-items-center " xmlns="http://www.w3.org/1999/html">
    
<!-- begin widget-list -->
<div class="row align-items-center justify-content-center">
    <div class="col-xl-6 col-lg-6 align-self-center">
    
    <div class="mb-10px mt-10px fs-10px">
    <b class="text-body h1">Applications</b>
    </div>
        <div class="widget-list rounded mb-4" data-id="widget">
            
                @foreach (var item in applications)
                {
                    <div class="row">
                        <a href="/Home/Dashboard/@item.Id" class="widget-list-item align-items-center col-11">
                            <div class="widget-list-media icon">
                                <i class="fa-brands fa-adn bg-dark text-white"></i>
                            </div>
                            <div class="widget-list-content">
                                <h4 class="widget-list-title">@item.Name</h4>
                            </div>
                        </a>
                        <a href="@Url.Action("DeleteApplication", "Home", new { id = item.Id })" class=" widget-list-item align-items-center col-1">
                            <i class="fa fa-trash fa-lg text-body text-red text-opacity-30"></i>
                        </a>
                    </div>
                }
            <a href="#modal-dialog" data-bs-toggle="modal" class="widget-list-item bg-transparent">
                <div class="widget-list-media icon">
                    <i class="fa-solid fa-plus text-white bg-dark"></i>
                </div>
                <div class="widget-list-content">
                    <h4 class="widget-list-title">Add new +</h4>
                </div>
            </a>
        </div>
        
        <!-- #modal-dialog -->
        <div class="modal fade" id="modal-dialog">
            <div class="modal-dialog">
                <form asp-action="CreateApplication" asp-controller="Home" method="post">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Add Application</h4>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-hidden="true"></button>
                        </div>
                        <div class="modal-body">
                            <div class="form-floating mb-20px">
                                <input type="text" class="form-control fs-13px h-45px" id="applicationName" placeholder="Application Name" asp-for="Name" autofocus required/>
                                <label for="applicationName" class="d-flex align-items-center">Application Name</label>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <a href="javascript:" class="btn btn-white" data-bs-dismiss="modal">Close</a>
                            <input class="btn btn-success" type="submit" value="Confirm"/>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    
    </div>
    <!-- end widget-list -->
    </div>

</div>